[project]
name = "src"
version = "0.0.1"
description = "Full end-to-end mlops pipline"
authors =[{name = "Muhammad khizer zakir",email = "muhammadkhizerzakir@gmail.com"}]

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}